BraincraftedBootstrapDemoBundle_index:
    pattern:  /bootstrap
    defaults: { _controller: BraincraftedBootstrapDemoBundle:Bootstrap:index }

BraincraftedBootstrapDemoBundle_gettingStarted:
    pattern:  /bootstrap/getting-started
    defaults: { _controller: BraincraftedBootstrapDemoBundle:Bootstrap:gettingStarted }

BraincraftedBootstrapDemoBundle_scaffolding:
    pattern:  /bootstrap/scaffolding
    defaults: { _controller: BraincraftedBootstrapDemoBundle:Bootstrap:scaffolding }

BraincraftedBootstrapDemoBundle_baseCss:
    pattern:  /bootstrap/base-css
    defaults: { _controller: BraincraftedBootstrapDemoBundle:Bootstrap:baseCss }

BraincraftedBootstrapDemoBundle_components:
    pattern:  /bootstrap/components
    defaults: { _controller: BraincraftedBootstrapDemoBundle:Bootstrap:components }

BraincraftedBootstrapDemoBundle_javascript:
    pattern:  /bootstrap/javascript
    defaults: { _controller: BraincraftedBootstrapDemoBundle:Bootstrap:javascript }

BraincraftedBootstrapDemoBundle_customize:
    pattern:  /bootstrap/customize
    defaults: { _controller: BraincraftedBootstrapDemoBundle:Bootstrap:customize }
